### ISSUE TITLE
Some tests are failing?

### ISSUE THREAD

**Issue by t-bast** [rustyrussell/lnprototest#4]
I wanted to give lnprototest a try to evaluate what changes would be needed on the eclair RPC to implement a runner, but I'm running into seemingly basic issues.

Is it expected that some tests are failing even with the dummy runner?

![lnprototest](https://user-images.githubusercontent.com/31281497/92738521-4ce82d00-f37c-11ea-9ee6-b2a19d30ed5e.png)

They're also all failing (but more slowly) with the clightning runner (using the [latest commit on master](https://github.com/ElementsProject/lightning/commit/9b41d608eeda42ed7f51462cb2e15129dceec9ba)), so I suspect that something's wrong with my installation (python is such a mess to get right for newbies...).

![lnprototest2](https://user-images.githubusercontent.com/31281497/92739929-a2710980-f37d-11ea-904b-3fdaefb62ff0.png)

I see these errors scattered in the output:

```
ValueError: ('Error waiting for {}', <function Runner.start.<locals>.<lambda> at 0x7fc82ec02b70>)
lnprototest.errors.SpecFileError: (Msg:test_bolt2-20-open_channel_accepter.py:71, 'Unknown msgtype open_channel2')
lnprototest.errors.SpecFileError: (ExpectMsg:test_bolt2-20-open_channel_accepter.py:216, 'Unknown msgtype tx_add_input')
AttributeError: 'PublicKey' object has no attribute 'secret'
```

**Comment by rustyrussell** [comment]
This is why I really should integrate this into our CI system :(

Thanks, will investigate!

**Comment by rustyrussell** [comment]
Gah, OK, bad code in refactor.  Fixed, thanks!

**Comment by t-bast** [comment]
Great thanks, that fixed it for the dummy runner!
However all tests are still failing with the c-lightning runner, is there a specific c-lightning commit I can use to get it to work?
That would be really helpful to start implementing an eclair runner, since I have no idea what exactly I need to do right now :)
