### ISSUE TITLE
ExpectError Should check that connection is closed or not

### ISSUE THREAD

**Issue by Psycho-Pirate** [rustyrussell/lnprototest#57]
I am making a LDK runner class to integrate LDK with Lnprototest. While running the BOLT#1 tests, I found out that the tests are failing because LDK is not sending an error message when the connection is closed because of protocol violations.

https://github.com/rustyrussell/lnprototest/blob/8efd45555ef3d1223f3b9f6a8c009419c9510747/tests/test_bolt1-02-unknown-messages.py#L29
Here LDK, closes the connection when it receives unknown even message but it fails the test because it does not send any error message.

On checking BOLT#1, I found out that sending a message after protocol violation is something a node SHOULD do and its not a MUST.
```
A sending node:

    SHOULD send error for protocol violations or internal errors that make channels unusable or that make further communication unusable.
```
https://github.com/lightning/bolts/blob/master/01-messaging.md#requirements-2

While I will be working on adding the error msg in LDK, I think Lnprototest should check for all the MUSTs in BOLTs instead of SHOULDs to accommodate more lightning implementations.
Instead of checking for error messages it should check that the connection is closed and made unusable by the node.

**Comment by vincenzopalazzo** [comment]
Yeah! this is a spec violation from lnprototest, sorry about that!

I will try to allocate some time to fix this in the next week! off course if you have the change ready PRs are welcome

**Comment by Psycho-Pirate** [comment]
I am not really sure on how to check if the node has closed the connection or not. Maybe we can use something like this
```
[
    Msg("init", globalfeatures="", features=bitfield(98)),
    ExpectMsg("init"),
]
```
By expecting an init message right after spec violation. We should check if this fails or not. If it fails the node has closed the connection.
Or we can update the `ExpectError` class to check for this.

**Comment by vincenzopalazzo** [comment]
Nah this is a hack! and from the spec you have no ruled IIRC that you can not send two init messages, so you can hide a bug.

Both in my vision are hacked. As suggested on Discord when you fall in your case, you should keep going and try to do expected operation after the init message, and these operation need to return an error

**Comment by Psycho-Pirate** [comment]
Okay. How can we check if the channel has been made unusable by the node?

**Comment by vincenzopalazzo** [comment]
After the init message we can not have a channel! So maybe you need to create a channel before? but I think during this operation you will fall in some other corner case with the integration.

If you want keep going next you can disable the test for a specific runner by the pytest keyword, but I do not have clear solution because I do not jump in the code yet
